/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.InmuebleData;
import Entidades.Inmueble;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MeD Servicios Inf
 */
public class BuscarInmueble extends javax.swing.JFrame {

        private Connection con;
        InmuebleData id = new InmuebleData();
        Inmueble inmu = null;
        private ArrayList<Entidades.Inmueble> listadoInmuebles;
        
        
public BuscarInmueble(Connection con) {
        this.con = con;	
	 } 

        private String [] zona = {"URBANA", "SUBURBANA", "RURAL"};
        private String [] tipoInmueble = {"CASA", "DEPARTAMENTO", "MONOAMBIENTE", "DUPLEX", "TERRENO", "LOCAL", "COMPLEJO", "OFICINA", "COCHERA", "DEPOSITO", "CABAÑA"};
	private DefaultTableModel modeloBuscarInmueble = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
        };
        
	public BuscarInmueble() {
            initComponents();
            cargarComboTipo();
            cargarComboZona();
            cargarComboSuperficie();
            editarModelo();
            
            listadoInmuebles = (ArrayList<Entidades.Inmueble>)id.listarInmueblePorId();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                jPanel1 = new javax.swing.JPanel();
                jLpropiedades = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                jLabel2 = new javax.swing.JLabel();
                jCBtipoInmueble = new javax.swing.JComboBox<>();
                jCBzona = new javax.swing.JComboBox<>();
                jCBsuperficie = new javax.swing.JComboBox<>();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTbuscarInmueble = new javax.swing.JTable();
                jBsalir = new javax.swing.JButton();
                jBreservarInmueble = new javax.swing.JButton();
                jBBUSCAR = new javax.swing.JButton();
                jLbuscarInmu = new javax.swing.JLabel();
                jLtipo = new javax.swing.JLabel();
                jLzona = new javax.swing.JLabel();
                jLsuperfMin = new javax.swing.JLabel();
                jButton3 = new javax.swing.JButton();

                jButton1.setText("jButton1");

                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
                jScrollPane1.setViewportView(jTextArea1);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLpropiedades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-la83-larga.png"))); // NOI18N
                jPanel1.add(jLpropiedades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 120));
                jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 410, 30));

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(204, 0, 0));
                jLabel2.setText("Inmuebles disponibles");
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 270, -1));

                jCBtipoInmueble.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
                jCBtipoInmueble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
                jCBtipoInmueble.setSelectedIndex(-1);
                jCBtipoInmueble.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jCBtipoInmuebleActionPerformed(evt);
                        }
                });
                jPanel1.add(jCBtipoInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 150, -1));

                jCBzona.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
                jCBzona.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jCBzonaActionPerformed(evt);
                        }
                });
                jPanel1.add(jCBzona, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

                jCBsuperficie.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
                jCBsuperficie.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jCBsuperficieActionPerformed(evt);
                        }
                });
                jPanel1.add(jCBsuperficie, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 60, -1));

                jTbuscarInmueble.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane2.setViewportView(jTbuscarInmueble);

                jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 90));

                jBsalir.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
                jBsalir.setForeground(new java.awt.Color(0, 0, 255));
                jBsalir.setText("SALIR");
                jBsalir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBsalirActionPerformed(evt);
                        }
                });
                jPanel1.add(jBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, -1, -1));

                jBreservarInmueble.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
                jBreservarInmueble.setForeground(new java.awt.Color(204, 0, 0));
                jBreservarInmueble.setText("RESERVAR INMUEBLE");
                jBreservarInmueble.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBreservarInmuebleActionPerformed(evt);
                        }
                });
                jPanel1.add(jBreservarInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

                jBBUSCAR.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
                jBBUSCAR.setForeground(new java.awt.Color(255, 51, 51));
                jBBUSCAR.setText("BUSCAR");
                jBBUSCAR.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBBUSCARActionPerformed(evt);
                        }
                });
                jPanel1.add(jBBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

                jLbuscarInmu.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
                jLbuscarInmu.setForeground(new java.awt.Color(0, 102, 102));
                jLbuscarInmu.setText("BUSCAR INMUEBLE");
                jPanel1.add(jLbuscarInmu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

                jLtipo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
                jLtipo.setText("TIPO:");
                jPanel1.add(jLtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

                jLzona.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
                jLzona.setText("ZONA:");
                jPanel1.add(jLzona, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

                jLsuperfMin.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
                jLsuperfMin.setText("SUPERFICIE HASTA:");
                jPanel1.add(jLsuperfMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

                jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
                jButton3.setForeground(new java.awt.Color(255, 0, 0));
                jButton3.setText("ELIMINAR");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });
                jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 22, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jCBtipoInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBtipoInmuebleActionPerformed
        modeloBuscarInmueble.setRowCount(0);

        
        String inm = (String) jCBtipoInmueble.getSelectedItem();
        //PREGUNTAR SI ACA HAY QUE HACER EL IF PARA EL CHAR DEL TIPO? O UN SWITCH
    }//GEN-LAST:event_jCBtipoInmuebleActionPerformed

    private void jCBzonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBzonaActionPerformed
        modeloBuscarInmueble.setRowCount(0);

        String inm = (String) jCBzona.getSelectedItem();
        
    }//GEN-LAST:event_jCBzonaActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        
        dispose();
    }//GEN-LAST:event_jBsalirActionPerformed
//revisar por qué no anda, solo quiero cargar los datos en la tabla 
    private void jBBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBUSCARActionPerformed
        modeloBuscarInmueble.setRowCount(0);

        
        int superficie = (int)jCBsuperficie.getSelectedItem();
        
        
        String tipo= (String) jCBtipoInmueble.getSelectedItem();
        
        String zona = (String) jCBzona.getSelectedItem();
        
        
        List<Inmueble> listadoInmuebles = new ArrayList<>();
        
        listadoInmuebles = id.listarInmueblesDe(superficie, tipo, zona);
        for (Inmueble i : listadoInmuebles) {
           
            
            modeloBuscarInmueble.addRow(new Object[]{
                i.getIdInmueble(),
                i.getPropietario().getIdPropietario(),
                i.getCaracteristicas(),
                i.getDireccion(),
                i.getPrecio(),
                i.getObservaciones(),});   
        }
    }//GEN-LAST:event_jBBUSCARActionPerformed

    private void jCBsuperficieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBsuperficieActionPerformed
        modeloBuscarInmueble.setRowCount(0);

        
    }//GEN-LAST:event_jCBsuperficieActionPerformed

    private void jBreservarInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBreservarInmuebleActionPerformed
        
        int idInmu = (int)jTbuscarInmueble.getValueAt(jTbuscarInmueble.getSelectedRow(), 0);
        
        id.reservarInmueble(idInmu);
                
    }//GEN-LAST:event_jBreservarInmuebleActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        Inmueble idInmuebleSeleccionado = (Inmueble) obtenerInmuebleSeleccionadoDeTabla();
        if (idInmuebleSeleccionado != null){
       id.eliminarInmueble(idInmuebleSeleccionado.getIdInmueble());
       

   }else {
       JOptionPane.showMessageDialog(this, "No hay un inmueble seleccionado");
   }
    }//GEN-LAST:event_jButton3ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(BuscarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(BuscarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(BuscarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(BuscarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new BuscarInmueble().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jBBUSCAR;
        private javax.swing.JButton jBreservarInmueble;
        private javax.swing.JButton jBsalir;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JComboBox<Integer> jCBsuperficie;
        private javax.swing.JComboBox<String> jCBtipoInmueble;
        private javax.swing.JComboBox<String> jCBzona;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLbuscarInmu;
        private javax.swing.JLabel jLpropiedades;
        private javax.swing.JLabel jLsuperfMin;
        private javax.swing.JLabel jLtipo;
        private javax.swing.JLabel jLzona;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JTable jTbuscarInmueble;
        private javax.swing.JTextArea jTextArea1;
        // End of variables declaration//GEN-END:variables
private void cargarComboTipo(){
     for(int i = 0; i < tipoInmueble.length; i++){
         jCBtipoInmueble.addItem(tipoInmueble[i]);
       }
}
private void cargarComboZona(){
          for(int i = 0; i < zona.length; i++){
         jCBzona.addItem(zona[i]);
       }  
}
private void cargarComboSuperficie(){
       for(int i = 15; i < 100; i++){
         jCBsuperficie.addItem(i);
         
       }
}
private void editarModelo(){
    
    modeloBuscarInmueble.addColumn("idInmueble");
    modeloBuscarInmueble.addColumn("idPropietario");
    modeloBuscarInmueble.addColumn("caracteristicas");
    modeloBuscarInmueble.addColumn("direccion");
    modeloBuscarInmueble.addColumn("precio");
    modeloBuscarInmueble.addColumn("observaciones");
    
    jTbuscarInmueble.setModel(modeloBuscarInmueble);
}
private Inmueble obtenerInmuebleSeleccionadoDeTabla() { 

	int filaSeleccionada = jTbuscarInmueble.getSelectedRow();
    
    if (filaSeleccionada != -1) {
        int idInmueble = (int) jTbuscarInmueble.getValueAt(filaSeleccionada, 0); // Suponiendo que la primera columna contiene el ID del inmueble

        
        
        for (Inmueble inmueble : listadoInmuebles) {
            if (inmueble.getIdInmueble() == idInmueble) {
                return inmueble; // Devuelve el Inmueble encontrado
            }
        }
    } 
            return null;

}
}
