/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author MeD Servicios Inf
 */
public class Contrato extends javax.swing.JFrame {

	/**
	 * Creates new form Contrato
	 */
	public Contrato() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                jLabel3 = new javax.swing.JLabel();
                cbxSeleccionInquilino = new javax.swing.JComboBox<>();
                jSeparator2 = new javax.swing.JSeparator();
                jLabel6 = new javax.swing.JLabel();
                jSeparator5 = new javax.swing.JSeparator();
                jLabel11 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tableContratos = new javax.swing.JTable();
                btnGuardar = new javax.swing.JButton();
                btnEditar = new javax.swing.JButton();
                btnCancelar = new javax.swing.JButton();
                btnSalir = new javax.swing.JButton();
                rbContratoActivo = new javax.swing.JRadioButton();
                rbContratoInactivo = new javax.swing.JRadioButton();
                jButton1 = new javax.swing.JButton();
                jLabel4 = new javax.swing.JLabel();
                cbxSeleccioneInmueble = new javax.swing.JComboBox<>();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MeD Servicios Inf\\Documents\\GitHub\\inmo-final\\src\\img\\icono-la83-larga.png")); // NOI18N
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 520, 120));

                jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(153, 0, 0));
                jLabel2.setText("CONTRATOS");
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

                jSeparator1.setForeground(new java.awt.Color(204, 0, 0));
                jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 470, 10));

                jLabel3.setText(" Seleccione Inquilino");
                jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

                jPanel1.add(cbxSeleccionInquilino, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 180, -1));

                jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
                jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 310, 10));

                jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(196, 107, 107));
                jLabel6.setText("Información del Contrato");
                jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

                jSeparator5.setForeground(new java.awt.Color(153, 0, 0));
                jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 760, 470, -1));

                jLabel11.setText("Propiedades La83 - ULP Red 1 AP - Desarrollo De Aplicaciones JAVA  ");
                jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 770, -1, -1));

                tableContratos.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane1.setViewportView(tableContratos);

                jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 470, 330));

                btnGuardar.setText("Guardar");
                jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, 110, 40));

                btnEditar.setText("Editar");
                jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 700, 110, 40));

                btnCancelar.setText("Cancelar");
                jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 700, 110, 40));

                btnSalir.setText("Salir");
                jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 700, 100, 40));

                rbContratoActivo.setText("Activo");
                jPanel1.add(rbContratoActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

                rbContratoInactivo.setText("Inactivo");
                jPanel1.add(rbContratoInactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

                jButton1.setText("Listar todos los contratos");
                jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 190, -1));

                jLabel4.setText("Seleccione Inmueble");
                jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

                jPanel1.add(cbxSeleccioneInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 190, -1));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Contrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Contrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Contrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Contrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Contrato().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCancelar;
        private javax.swing.JButton btnEditar;
        private javax.swing.JButton btnGuardar;
        private javax.swing.JButton btnSalir;
        private javax.swing.JComboBox<String> cbxSeleccionInquilino;
        private javax.swing.JComboBox<String> cbxSeleccioneInmueble;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JSeparator jSeparator5;
        private javax.swing.JRadioButton rbContratoActivo;
        private javax.swing.JRadioButton rbContratoInactivo;
        private javax.swing.JTable tableContratos;
        // End of variables declaration//GEN-END:variables
}
