/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.InmuebleData;
import Entidades.Inmueble;
import Entidades.Inquilino;
import Entidades.Propietario;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kelly
 */
public class ListarInmueble extends javax.swing.JFrame {
private Connection con;
private InmuebleData id = new InmuebleData();
private Inquilino inq = new Inquilino();
private Propietario pro = new Propietario();
private Inmueble inmu = null;
private ArrayList<Entidades.Inmueble> listadoInmuebles;

    
    public ListarInmueble(Connection con) {
        this.con = con;
    }
    
    private DefaultTableModel modeloListarInmueble = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
        };

    public ListarInmueble(){
        initComponents();
        editarModelo();
        limpiarCampos(); 
//        listadoInmuebles = (ArrayList<Entidades.Inmueble>)id.listarInmueblePorDniInqui(); //por parametro me pide id propietario
//        listadoInmuebles = (ArrayList<Entidades.Inmueble>)id.listarInmueblePorDniProp(); //por parametro me pide dni inquilino
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel2 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                jLlistarInmueble = new javax.swing.JLabel();
                jLDniInquilino = new javax.swing.JLabel();
                jTdniInquilino = new javax.swing.JTextField();
                jLdniPropietario = new javax.swing.JLabel();
                jTdniProp = new javax.swing.JTextField();
                jBbuscarDniInq = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTlistado = new javax.swing.JTable();
                jBsalir = new javax.swing.JButton();
                jBlimpiar = new javax.swing.JButton();
                jBdniProp = new javax.swing.JButton();

                jLabel2.setText("jLabel2");

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane1.setViewportView(jTable1);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MeD Servicios Inf\\Documents\\GitHub\\inmo-final\\src\\img\\icono-la83-larga.png")); // NOI18N

                jLlistarInmueble.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
                jLlistarInmueble.setForeground(new java.awt.Color(204, 0, 0));
                jLlistarInmueble.setText("Listar Inmueble");

                jLDniInquilino.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
                jLDniInquilino.setText("DNI INQUILINO:");

                jTdniInquilino.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTdniInquilinoActionPerformed(evt);
                        }
                });
                jTdniInquilino.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                                jTdniInquilinoKeyTyped(evt);
                        }
                });

                jLdniPropietario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
                jLdniPropietario.setText("DNI PROPIETARIO:");

                jTdniProp.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTdniPropActionPerformed(evt);
                        }
                });
                jTdniProp.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                                jTdniPropKeyTyped(evt);
                        }
                });

                jBbuscarDniInq.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
                jBbuscarDniInq.setForeground(new java.awt.Color(255, 0, 51));
                jBbuscarDniInq.setText("BUSCAR");
                jBbuscarDniInq.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBbuscarDniInqActionPerformed(evt);
                        }
                });

                jTlistado.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane2.setViewportView(jTlistado);

                jBsalir.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
                jBsalir.setForeground(new java.awt.Color(51, 51, 255));
                jBsalir.setText("SALIR");
                jBsalir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBsalirActionPerformed(evt);
                        }
                });

                jBlimpiar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
                jBlimpiar.setForeground(new java.awt.Color(0, 153, 0));
                jBlimpiar.setText("LIMPIAR");
                jBlimpiar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBlimpiarActionPerformed(evt);
                        }
                });

                jBdniProp.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
                jBdniProp.setForeground(new java.awt.Color(255, 0, 51));
                jBdniProp.setText("BUSCAR");
                jBdniProp.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBdniPropActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLlistarInmueble, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jSeparator1)
                                                .addGap(80, 80, 80))
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLDniInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLdniPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jTdniInquilino, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jTdniProp)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jBbuscarDniInq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBdniProp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addComponent(jBlimpiar)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(182, 182, 182)
                                                .addComponent(jBsalir)
                                                .addGap(82, 82, 82))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLlistarInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLDniInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTdniInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jBbuscarDniInq))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLdniPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTdniProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jBdniProp)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jBsalir)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jBlimpiar)))
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jTdniInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdniInquilinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdniInquilinoActionPerformed

    private void jBbuscarDniInqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarDniInqActionPerformed
        modeloListarInmueble.setRowCount(0);
        
         try {              
            long dniInqui = Long.parseLong(jTdniInquilino.getText());

        listadoInmuebles = id.listarInmueblePorDniInqui((int) dniInqui);
             
        for (Inmueble i : listadoInmuebles) {
            int list= 0;
           if (i.getOcupante()!= null){
               list= i.getOcupante().getIdInquilino();
           }
            
            modeloListarInmueble.addRow(new Object[]{
               
                i.getIdInmueble(),                
                list,
                i.getPropietario().getIdPropietario(),
                i.getCaracteristicas(),
                i.getDireccion(),
                i.getZona(),
                i.getTipoInmueble(),
                i.getPrecio(),
                i.getObservaciones(),
                i.getEstado(),});   
        }
      
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Debe ingresar un documento válido");
        }
    }//GEN-LAST:event_jBbuscarDniInqActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
       dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jTdniInquilinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdniInquilinoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "SOLO PUEDE INGRESAR NUMEROS ");
        }
    }//GEN-LAST:event_jTdniInquilinoKeyTyped

    private void jTdniPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdniPropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdniPropActionPerformed

    private void jTdniPropKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdniPropKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "SOLO PUEDE INGRESAR NUMEROS ");
        }
    }//GEN-LAST:event_jTdniPropKeyTyped

    private void jBlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimpiarActionPerformed
        limpiarCampos();
        inmu = null;
    }//GEN-LAST:event_jBlimpiarActionPerformed

    private void jBdniPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdniPropActionPerformed
        modeloListarInmueble.setRowCount(0);
         try {
//              
            
            long dniProp = Long.parseLong(jTdniProp.getText());
//             List<Inmueble> listadoInmuebles = new ArrayList<>();
        
        
        listadoInmuebles = id.listarInmueblePorDniProp((int) dniProp);
        for (Inmueble i : listadoInmuebles) {

            int list= 0;
           if (i.getOcupante()!= null){
               list= i.getOcupante().getIdInquilino();
           }
            modeloListarInmueble.addRow(new Object[]{
                
                i.getIdInmueble(),
                list,
                i.getPropietario().getIdPropietario(),
                i.getCaracteristicas(),
                i.getDireccion(),
                i.getZona(),
                i.getTipoInmueble(),
                i.getPrecio(),
                i.getObservaciones(),
                i.getEstado(),});   
        }
      
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Debe ingresar un documento válido");
        }
                                         
    }//GEN-LAST:event_jBdniPropActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarInmueble().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jBbuscarDniInq;
        private javax.swing.JButton jBdniProp;
        private javax.swing.JButton jBlimpiar;
        private javax.swing.JButton jBsalir;
        private javax.swing.JLabel jLDniInquilino;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLdniPropietario;
        private javax.swing.JLabel jLlistarInmueble;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JTable jTable1;
        private javax.swing.JTextField jTdniInquilino;
        private javax.swing.JTextField jTdniProp;
        private javax.swing.JTable jTlistado;
        // End of variables declaration//GEN-END:variables
private void editarModelo(){
    
    
    modeloListarInmueble.addColumn("idInmueble");
    modeloListarInmueble.addColumn("idInquilino");
    modeloListarInmueble.addColumn("idPropietario");
    modeloListarInmueble.addColumn("caracteristicas");
    modeloListarInmueble.addColumn("direccion");
    modeloListarInmueble.addColumn("zona");
    modeloListarInmueble.addColumn("tipoInmueble");
    modeloListarInmueble.addColumn("precio");
    modeloListarInmueble.addColumn("observaciones");
    modeloListarInmueble.addColumn("estado");
    jTlistado.setModel(modeloListarInmueble);
}
private void limpiarCampos() {
       jTdniInquilino.setText("");
        jTdniProp.setText("");
//       jTlistado.setSelected("");//para limpiar la tabla tambien al momento de hacer una nueva bsuqueda
}

}
